doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Product:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Entity'
                prefix: 'App\Product\Entity'
                alias: App\Product
            MealView:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/View'
                prefix: 'App\Product\View\MealView'
                alias: App\Product\MealView
            ProductView:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/View'
                prefix: 'App\Product\View\ProductView'
                alias: App\Product\ProductView
            NutritionLog:
                is_bundle: false
                dir: '%kernel.project_dir%/src/NutritionLog/Entity'
                prefix: 'App\NutritionLog\Entity'
                alias: App\NutritionLog

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
