monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - info

  handlers:
    main:
      type: rotating_file
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: warning
      max_files: 10
    nested:
      type: stream
      path: php://stderr
      level: warning
      formatter: monolog.formatter.json
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine" ]
    info:
      type: rotating_file
      path: '%kernel.logs_dir%/info.log'
      level: debug
      max_files: 10
      channels: [ info ]