image: docker:20.10

services:
  - docker:20.10-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: 1

stages:
  - test

tests_warmup:
  stage: test
  script:
    - docker-compose build tests_unit
    - docker-compose run --rm tests_unit
