version: '3.6'

services:

  tests_unit:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: static_analysis

  tests_architecture:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: static_analysis
    command: [ "composer", "tests:architecture" ]

  app:
    container_name: add2_backend_api
    build:
      context: .
      dockerfile: ./docker/web_app/Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - "8888:80"
    networks:
      - add2_backend

  db:
    image: mysql:8.0.23
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "app-db-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Rand0m
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: Rand0m
    ports:
      - 3306:3306
    networks:
      - add2_backend

  dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
      - app
    command: db:3306
    networks:
      - add2_backend

volumes:
  app-volume:
  app-db-volume:

networks:
  add2_backend:
    external: true