version: '3.6'

services:

  app:
    container_name: core_api
    build:
      target: dev
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/app/
    expose:
      - 9000
    networks:
      - amciu_backend
      - amciu_core_api

  proxy:
    container_name: core_api_proxy
    build:
      context: .
      dockerfile: ./docker/proxy/Dockerfile
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "82:80"
    networks:
      - amciu_core_api
      - amciu_backend

  db:
    container_name: core_api_db
    image: mysql:8.0.23
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "app-db-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Rand0m
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: Rand0m
    ports:
      - 3306:3306
    networks:
      - amciu_core_api

  dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
      - app
    command: db:3306
    networks:
      - amciu_backend
      - amciu_core_api

volumes:
  app-db-volume:

networks:
  amciu_backend:
    external: true
  amciu_core_api:
