version: '3.6'

services:

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - "8888:80"

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: dev
    volumes:
      - ./public/:/app/public/
      - ./tools/:/app/tools/
      - ./src/:/app/src/
      - ./var/:/app/var/
      - ./config/:/app/config/
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./resources/:/app/resources/
      - ./symfony.lock/:/app/symfony.lock/
      - ./.env/:/app/.env/
      - app-volume:/app/
    expose:
      - 9000

volumes:
  app-volume:
