version: '3.6'

services:

  app:
    container_name: core_api
    build:
      context: .
      dockerfile: ./docker/web_app/Dockerfile
    volumes:
      - ./:/var/www/html/
    expose:
      - 9000
    networks:
      - amciu_backend

  db:
    container_name: core_api_db
    image: mysql:8.0.23
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "app-db-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Rand0m
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: Rand0m
    ports:
      - 3306:3306
    networks:
      - amciu_backend

  dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
      - app
    command: db:3306
    networks:
      - amciu_backend

volumes:
  app-volume:
  app-db-volume:

networks:
  amciu_backend:
    external: true