version: '3.6'

services:

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - "8888:80"

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: dev
    volumes:
      - ./:/app/
    expose:
      - 9000

volumes:
  app-volume:
