monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

  handlers:
    sentry:
      type: sentry
      level: error
      hub_id: Sentry\State\HubInterface
      dsn: '%env(SENTRY_DSN)%'


