product:
    resource:
        path: ../src/Catalog/Controller/
        namespace: App\Catalog\Controller
    type: attribute

nutrition_log:
    resource:
        path: ../src/NutritionLog/Controller/
        namespace: App\NutritionLog\Controller
    type: attribute

metrics:
    resource:
        path: ../src/Metric/Controller/
        namespace: App\Metric\Controller
    type: attribute
